const data = {
  CODE: 200,
  STATUS: "SUCCESS",
  MESSAGE: "",
  TOTAL_RECORDS: 53,
  RESPONSE: [
    {
      UNIQUE_QUERY_ID: "2541550594",
      QUERY_TYPE: "W",
      QUERY_TIME: "2023-09-05 00:00:19",
      SENDER_NAME: "Manish",
      SENDER_MOBILE: "+91-9910382521",
      SENDER_EMAIL: "",
      SUBJECT: "Requirement for Plain W Cut Non Woven Bag",
      SENDER_COMPANY: "",
      SENDER_ADDRESS: "Delhi, Delhi",
      SENDER_CITY: "Delhi",
      SENDER_STATE: "Delhi",
      SENDER_PINCODE: "",
      SENDER_COUNTRY_ISO: "IN",
      SENDER_MOBILE_ALT: "",
      SENDER_PHONE: "",
      SENDER_PHONE_ALT: "",
      SENDER_EMAIL_ALT: "",
      QUERY_PRODUCT_NAME: "Plain W Cut Non Woven Bag",
      QUERY_MESSAGE: "I am interested in Plain W Cut Non Woven Bag<br>",
      QUERY_MCAT_NAME: "Non Woven W Cut Bags",
      CALL_DURATION: "",
      RECEIVER_MOBILE: "",
    },
    {
      UNIQUE_QUERY_ID: "2541675997",
      QUERY_TYPE: "W",
      QUERY_TIME: "2023-09-05 09:30:57",
      SENDER_NAME: "Manjushri Goke",
      SENDER_MOBILE: "+91-9579476640",
      SENDER_EMAIL: "manjushrigokhe113@gmail.com",
      SUBJECT:
        "Requirement for White D Cut Non Woven Shopping Bag, Capacity: 5 kg",
      SENDER_COMPANY: "",
      SENDER_ADDRESS: "Nagpur, Maharashtra,         440024",
      SENDER_CITY: "Nagpur",
      SENDER_STATE: "Maharashtra",
      SENDER_PINCODE: "440024",
      SENDER_COUNTRY_ISO: "IN",
      SENDER_MOBILE_ALT: "",
      SENDER_PHONE: "",
      SENDER_PHONE_ALT: "",
      SENDER_EMAIL_ALT: "",
      QUERY_PRODUCT_NAME: "White D Cut Non Woven Shopping Bag, Capacity: 5 kg",
      QUERY_MESSAGE:
        "I am interested in White D Cut Non Woven Shopping Bag, Capacity: 5 kg<br>",
      QUERY_MCAT_NAME: "D-Cut Non Woven Bags",
      CALL_DURATION: "",
      RECEIVER_MOBILE: "",
    },
    {
      UNIQUE_QUERY_ID: "95576089",
      QUERY_TYPE: "P",
      QUERY_TIME: "2023-09-05 14:47:33",
      SENDER_NAME: "Gulal Tiwari",
      SENDER_MOBILE: "+91-6294931701",
      SENDER_EMAIL: "tewarib06@gmail.com",
      SUBJECT: "Buyer Call",
      SENDER_COMPANY: "ms mobile gallery",
      SENDER_ADDRESS: "Murshidabad, West Bengal",
      SENDER_CITY: "Murshidabad",
      SENDER_STATE: "West Bengal",
      SENDER_PINCODE: "",
      SENDER_COUNTRY_ISO: "IN",
      SENDER_MOBILE_ALT: "+91-7699549474",
      SENDER_PHONE: "",
      SENDER_PHONE_ALT: "",
      SENDER_EMAIL_ALT: "dulaltewari9@gmail.com",
      QUERY_PRODUCT_NAME: "Non Woven W Cut Bags",
      QUERY_MESSAGE: "",
      QUERY_MCAT_NAME: "",
      CALL_DURATION: "88",
      RECEIVER_MOBILE: "9253186178",
    },
    {
      UNIQUE_QUERY_ID: "2542190567",
      QUERY_TYPE: "W",
      QUERY_TIME: "2023-09-05 17:13:29",
      SENDER_NAME: "Kapil Goyal",
      SENDER_MOBILE: "+91-9996149489",
      SENDER_EMAIL: "",
      SUBJECT: "Requirement for Non Woven Bag Fabric",
      SENDER_COMPANY: "Sandeep Sales",
      SENDER_ADDRESS: "Sonipat Haryana, Bhiwani, Haryana,         131001",
      SENDER_CITY: "Bhiwani",
      SENDER_STATE: "Haryana",
      SENDER_PINCODE: "131001",
      SENDER_COUNTRY_ISO: "IN",
      SENDER_MOBILE_ALT: "",
      SENDER_PHONE: "",
      SENDER_PHONE_ALT: "",
      SENDER_EMAIL_ALT: "",
      QUERY_PRODUCT_NAME: "Non Woven Bag Fabric",
      QUERY_MESSAGE:
        "I want to buy Non Woven Bag Fabric.Kindly send me price and other details. from bhiwani<br>Quantity : 40000<br>Quantity Unit : Kg<br>Probable Order Value : Rs. 36,00,000 - 52,00,000<br>Probable Requirement Type : Business Use<br>",
      QUERY_MCAT_NAME: "Bag Fabric",
      CALL_DURATION: "",
      RECEIVER_MOBILE: "",
    },
    {
      UNIQUE_QUERY_ID: "2542399820",
      QUERY_TYPE: "W",
      QUERY_TIME: "2023-09-05 21:00:50",
      SENDER_NAME: "MANOHAR",
      SENDER_MOBILE: "+91-9381592186",
      SENDER_EMAIL: "manoharc344@gmail.com",
      SUBJECT: "Requirement for Theme Background Clothes",
      SENDER_COMPANY: "MANOHAR GEMS",
      SENDER_ADDRESS: "Secunderabad, Telangana,         500044",
      SENDER_CITY: "Secunderabad",
      SENDER_STATE: "Telangana",
      SENDER_PINCODE: "500044",
      SENDER_COUNTRY_ISO: "IN",
      SENDER_MOBILE_ALT: "",
      SENDER_PHONE: "",
      SENDER_PHONE_ALT: "",
      SENDER_EMAIL_ALT: "",
      QUERY_PRODUCT_NAME: "Theme Background Clothes",
      QUERY_MESSAGE:
        "My Requirement is for Theme Background Clothes. Kindly send me price and other details.<br>Quantity : 20<br>Quantity Unit : Ton<br>Type of Requirement : Sample Only<br>Probable Requirement Type : Business Use<br>",
      QUERY_MCAT_NAME: "Non Woven Cloth",
      CALL_DURATION: "",
      RECEIVER_MOBILE: "",
    },
    {
      UNIQUE_QUERY_ID: "2542460362",
      QUERY_TYPE: "W",
      QUERY_TIME: "2023-09-05 22:32:27",
      SENDER_NAME: "Akash Deep",
      SENDER_MOBILE: "+91-8837889546",
      SENDER_EMAIL: "akash.anku0289@gmail.com",
      SUBJECT: "Requirement for Non Woven Stitched Bags",
      SENDER_COMPANY: "Kanyathi EcoCrafts",
      SENDER_ADDRESS:
        "Ward no. 3, Dinanagar, Gurdaspur, Punjab,         143531",
      SENDER_CITY: "Gurdaspur",
      SENDER_STATE: "Punjab",
      SENDER_PINCODE: "143531",
      SENDER_COUNTRY_ISO: "IN",
      SENDER_MOBILE_ALT: "",
      SENDER_PHONE: "",
      SENDER_PHONE_ALT: "",
      SENDER_EMAIL_ALT: "",
      QUERY_PRODUCT_NAME: "Non Woven Stitched Bags",
      QUERY_MESSAGE:
        "I need to resell this product and order will on weekly basis minimum quantity 500<br>Color : White/Yellow/Green<br>Quantity : 500<br>Quantity Unit : Piece<br>Size/Dimension : Customized<br>Probable Order Value : Rs. 6,000 - 9,000<br>Probable Requirement Type : Business Use<br>",
      QUERY_MCAT_NAME: "Stitched Non Woven Bags",
      CALL_DURATION: "",
      RECEIVER_MOBILE: "",
    },
    {
      UNIQUE_QUERY_ID: "2542869806",
      QUERY_TYPE: "W",
      QUERY_TIME: "2023-09-06 13:02:10",
      SENDER_NAME: "Shreya Rajendra Bansod",
      SENDER_MOBILE: "+91-9766705184",
      SENDER_EMAIL: "",
      SUBJECT: "Requirement for Waxing Strips",
      SENDER_COMPANY: "Shreya Bansod Constructions",
      SENDER_ADDRESS:
        "Rajapeth Amravati,Jalaram Nagar,Prabha Colony,Amravati,Amravati, Amravati, Maharashtra,         444601",
      SENDER_CITY: "Amravati",
      SENDER_STATE: "Maharashtra",
      SENDER_PINCODE: "444601",
      SENDER_COUNTRY_ISO: "IN",
      SENDER_MOBILE_ALT: "",
      SENDER_PHONE: "",
      SENDER_PHONE_ALT: "",
      SENDER_EMAIL_ALT: "",
      QUERY_PRODUCT_NAME: "Waxing Strips",
      QUERY_MESSAGE:
        "I want to buy Waxing Strips.\r\rKindly send me price and other details.<br>Quantity : 50<br>Quantity Unit : Pack<br>Type of Requirement : Monthly<br>Probable Order Value : Rs. 1,000 to 3,000<br>Why do you need this : Reselling<br>",
      QUERY_MCAT_NAME: "Waxing Strips",
      CALL_DURATION: "",
      RECEIVER_MOBILE: "",
    },
    {
      UNIQUE_QUERY_ID: "2543030331",
      QUERY_TYPE: "W",
      QUERY_TIME: "2023-09-06 15:20:18",
      SENDER_NAME: "Kamal Bansal",
      SENDER_MOBILE: "+91-8708859195",
      SENDER_EMAIL: "kamalbansal729@gmail.com",
      SUBJECT: "Requirement for White Max Pickup Bag",
      SENDER_COMPANY: "Bansal Disposable",
      SENDER_ADDRESS: "Bansal Disposal Store, Bhiwani, Haryana,         127021",
      SENDER_CITY: "Bhiwani",
      SENDER_STATE: "Haryana",
      SENDER_PINCODE: "127021",
      SENDER_COUNTRY_ISO: "IN",
      SENDER_MOBILE_ALT: "",
      SENDER_PHONE: "",
      SENDER_PHONE_ALT: "",
      SENDER_EMAIL_ALT: "",
      QUERY_PRODUCT_NAME: "White Max Pickup Bag",
      QUERY_MESSAGE:
        "I am interested in White Max Pickup Bag, Thickness: 51 Microns<br>Color : White<br>Thickness : 51 Microns<br>Probable Requirement Type : Business Use<br>",
      QUERY_MCAT_NAME: "Carry Bag",
      CALL_DURATION: "",
      RECEIVER_MOBILE: "",
    },
    {
      UNIQUE_QUERY_ID: "696997174",
      QUERY_TYPE: "B",
      QUERY_TIME: "2023-09-06 21:31:15",
      SENDER_NAME: "Rajesh Gupta",
      SENDER_MOBILE: "+91-9311642676",
      SENDER_EMAIL: "krishnagupta11112003@gmail.com",
      SUBJECT: "Requirement for Non Woven D Cut Bag",
      SENDER_COMPANY: "Gupta Sons Collections",
      SENDER_ADDRESS:
        "D4/26, Near Police Thana Road, Sangam Vihar, New Delhi-62, South Delhi, New Delhi, Delhi,         110062",
      SENDER_CITY: "New Delhi",
      SENDER_STATE: "Delhi",
      SENDER_PINCODE: "110062",
      SENDER_COUNTRY_ISO: "IN",
      SENDER_MOBILE_ALT: "+91-8851159598",
      SENDER_PHONE: "",
      SENDER_PHONE_ALT: "",
      SENDER_EMAIL_ALT: "",
      QUERY_PRODUCT_NAME: "Non Woven D Cut Bag",
      QUERY_MESSAGE:
        "I want to buy non woven bag.semi freshKindly send me price and other details.<br>Bag Type : D Cut Bag<br>Quantity : 200 Kg<br>Type of Requirement : Monthly<br>Probable Order Value : Rs. 25,000 - 35,000<br>Probable Requirement Type : Business Use<br>",
      QUERY_MCAT_NAME: "D-Cut Non Woven Bags",
      CALL_DURATION: "",
      RECEIVER_MOBILE: "",
    },
    {
      UNIQUE_QUERY_ID: "696997784",
      QUERY_TYPE: "B",
      QUERY_TIME: "2023-09-06 21:35:48",
      SENDER_NAME: "Navrang Gupta",
      SENDER_MOBILE: "+91-9580091514",
      SENDER_EMAIL: "pramodtraderspramodtraders@gmail.com",
      SUBJECT: "Requirement for Multicolor W Cut Non Woven Bags",
      SENDER_COMPANY: "Pramod Traders",
      SENDER_ADDRESS:
        "706, Kosi Parikrama Road, Ayodhya, Ayodhya, Uttar Pradesh,         224123",
      SENDER_CITY: "Ayodhya",
      SENDER_STATE: "Uttar Pradesh",
      SENDER_PINCODE: "224123",
      SENDER_COUNTRY_ISO: "IN",
      SENDER_MOBILE_ALT: "+91-9142427419",
      SENDER_PHONE: "",
      SENDER_PHONE_ALT: "",
      SENDER_EMAIL_ALT: "",
      QUERY_PRODUCT_NAME: "Multicolor W Cut Non Woven Bags",
      QUERY_MESSAGE:
        "I want to purchase Multicolor W Cut Non Woven Bags. Kindly send me price and other details.<br>Pattern : Plain<br>Usage/Application : Shopping<br>Probable Requirement Type : Business Use<br>",
      QUERY_MCAT_NAME: "Non Woven W Cut Bags",
      CALL_DURATION: "",
      RECEIVER_MOBILE: "",
    },
    {
      UNIQUE_QUERY_ID: "696997817",
      QUERY_TYPE: "B",
      QUERY_TIME: "2023-09-06 21:36:01",
      SENDER_NAME: "Priyatosh",
      SENDER_MOBILE: "+91-6294146330",
      SENDER_EMAIL: "priyatosh.official@gmail.com",
      SUBJECT: "Requirement for NON Woven Coloured Fabric",
      SENDER_COMPANY: "Painting Printers",
      SENDER_ADDRESS: "Kolkata, West Bengal",
      SENDER_CITY: "Kolkata",
      SENDER_STATE: "West Bengal",
      SENDER_PINCODE: "",
      SENDER_COUNTRY_ISO: "IN",
      SENDER_MOBILE_ALT: "",
      SENDER_PHONE: "",
      SENDER_PHONE_ALT: "",
      SENDER_EMAIL_ALT: "",
      QUERY_PRODUCT_NAME: "NON Woven Coloured Fabric",
      QUERY_MESSAGE:
        "I want to buy NON Woven Coloured Fabric. Kindly send me price and other details.<br>GSM : 60<br>Material : Polypropylene(PP)<br>Probable Requirement Type : Business Use<br>",
      QUERY_MCAT_NAME: "PP Spunbond Nonwoven Fabric",
      CALL_DURATION: "",
      RECEIVER_MOBILE: "",
    },
    {
      UNIQUE_QUERY_ID: "696998085",
      QUERY_TYPE: "B",
      QUERY_TIME: "2023-09-06 21:37:55",
      SENDER_NAME: "C.P Sharma",
      SENDER_MOBILE: "+91-9799888117",
      SENDER_EMAIL: "sharmabag17186@gmail.com",
      SUBJECT: "Requirement for Rangoli Thank U Shoppe Bags",
      SENDER_COMPANY: "Sharma Bags",
      SENDER_ADDRESS:
        "L-29, Sagar Vihar Colony, Vaishali Nagar, Ajmer, Rajasthan,         305001",
      SENDER_CITY: "Ajmer",
      SENDER_STATE: "Rajasthan",
      SENDER_PINCODE: "305001",
      SENDER_COUNTRY_ISO: "IN",
      SENDER_MOBILE_ALT: "+91-9982233390",
      SENDER_PHONE: "",
      SENDER_PHONE_ALT: "",
      SENDER_EMAIL_ALT: "",
      QUERY_PRODUCT_NAME: "Rangoli Thank U Shoppe Bags",
      QUERY_MESSAGE:
        "I want to buy Rangoli Thank U Shoppe Bags. Kindly send me price and other details.<br>Quantity : 500 Kg<br>Probable Order Value : Rs. 65,000 - 68,000<br>Probable Requirement Type : Business Use<br>",
      QUERY_MCAT_NAME: "Non Woven Bag",
      CALL_DURATION: "",
      RECEIVER_MOBILE: "",
    },
    {
      UNIQUE_QUERY_ID: "2543411371",
      QUERY_TYPE: "W",
      QUERY_TIME: "2023-09-06 23:21:08",
      SENDER_NAME: "Aman Verma",
      SENDER_MOBILE: "+91-7857054453",
      SENDER_EMAIL: "akvermaaman95@gmail.com",
      SUBJECT: "Requirement for Laminated Non Woven Fabric",
      SENDER_COMPANY: "Darshika Trading",
      SENDER_ADDRESS:
        "256 ward no 6 main road Birpur, Birpur, Bihar,         854340",
      SENDER_CITY: "Birpur",
      SENDER_STATE: "Bihar",
      SENDER_PINCODE: "854340",
      SENDER_COUNTRY_ISO: "IN",
      SENDER_MOBILE_ALT: "",
      SENDER_PHONE: "",
      SENDER_PHONE_ALT: "",
      SENDER_EMAIL_ALT: "",
      QUERY_PRODUCT_NAME: "Laminated Non Woven Fabric",
      QUERY_MESSAGE: "I am interested in Laminated Non Woven Fabric<br>",
      QUERY_MCAT_NAME: "Laminated Non Woven Fabric",
      CALL_DURATION: "",
      RECEIVER_MOBILE: "",
    },
    {
      UNIQUE_QUERY_ID: "2543793176",
      QUERY_TYPE: "W",
      QUERY_TIME: "2023-09-07 12:52:18",
      SENDER_NAME: "Natassha Brar",
      SENDER_MOBILE: "+91-7411047561",
      SENDER_EMAIL: "kbtrader9@gmail.com",
      SUBJECT: "Requirement for Non Woven For Footwear Packaging",
      SENDER_COMPANY: "KB  Traders",
      SENDER_ADDRESS: "Bengaluru, Karnataka,         560049",
      SENDER_CITY: "Bengaluru",
      SENDER_STATE: "Karnataka",
      SENDER_PINCODE: "560049",
      SENDER_COUNTRY_ISO: "IN",
      SENDER_MOBILE_ALT: "",
      SENDER_PHONE: "",
      SENDER_PHONE_ALT: "",
      SENDER_EMAIL_ALT: "",
      QUERY_PRODUCT_NAME: "Non Woven For Footwear Packaging",
      QUERY_MESSAGE:
        "I am interested in Thread Seal non woven for footwear packaging, 30 Gsm<br>",
      QUERY_MCAT_NAME: "Non Woven Shoes Bag",
      CALL_DURATION: "",
      RECEIVER_MOBILE: "",
    },
    {
      UNIQUE_QUERY_ID: "697322496",
      QUERY_TYPE: "B",
      QUERY_TIME: "2023-09-07 14:12:06",
      SENDER_NAME: "Khiyal R Mandhwani",
      SENDER_MOBILE: "+91-9049035208",
      SENDER_EMAIL: "krmandhwani29@gmail.com",
      SUBJECT: "Requirement for Non Woven D Cut Shopping Bag",
      SENDER_COMPANY: "Yasraj Home Aslisence",
      SENDER_ADDRESS: "Jalgaon, Maharashtra",
      SENDER_CITY: "Jalgaon",
      SENDER_STATE: "Maharashtra",
      SENDER_PINCODE: "",
      SENDER_COUNTRY_ISO: "IN",
      SENDER_MOBILE_ALT: "",
      SENDER_PHONE: "",
      SENDER_PHONE_ALT: "",
      SENDER_EMAIL_ALT: "",
      QUERY_PRODUCT_NAME: "Non Woven D Cut Shopping Bag",
      QUERY_MESSAGE:
        "I want to buy Non Woven D Cut Shopping Bag. Kindly send me price and other details.<br>Bag Type : D Cut Bag<br>Capacity : 3 Kg<br>Quantity : 500 Kg<br>Probable Order Value : Rs. 48,000 - 62,000<br>Probable Requirement Type : Business Use<br>",
      QUERY_MCAT_NAME: "D-Cut Non Woven Bags",
      CALL_DURATION: "",
      RECEIVER_MOBILE: "",
    },
    {
      UNIQUE_QUERY_ID: "697322801",
      QUERY_TYPE: "B",
      QUERY_TIME: "2023-09-07 14:12:50",
      SENDER_NAME: "Neeraj Gupta",
      SENDER_MOBILE: "+91-9796468341",
      SENDER_EMAIL: "aryanschool@hotmail.com",
      SUBJECT: "Requirement for Non Woven Multicolor Fabric Printed Roll",
      SENDER_COMPANY: "Aryan Public Sr. Sec School",
      SENDER_ADDRESS: "Ward No. 13, Dablehar Road, Jammu, Jammu & Kashmir",
      SENDER_CITY: "Jammu",
      SENDER_STATE: "Jammu & Kashmir",
      SENDER_PINCODE: "",
      SENDER_COUNTRY_ISO: "IN",
      SENDER_MOBILE_ALT: "+91-7051193235",
      SENDER_PHONE: "+(91)-(1923)-251925",
      SENDER_PHONE_ALT: "",
      SENDER_EMAIL_ALT: "",
      QUERY_PRODUCT_NAME: "Non Woven Multicolor Fabric Printed Roll",
      QUERY_MESSAGE:
        "My Requirement is for Non Woven Multicolor Fabric Printed Roll. Kindly send me price and other details.<br>GSM : 20 TO 200<br>Material : Polypropylene(PP)<br>Quantity : 100 Kg<br>Probable Order Value : Rs. 10,000 - 11,000<br>Probable Requirement Type : Business Use<br>",
      QUERY_MCAT_NAME: "Non Woven Fabric",
      CALL_DURATION: "",
      RECEIVER_MOBILE: "",
    },
    {
      UNIQUE_QUERY_ID: "697464895",
      QUERY_TYPE: "B",
      QUERY_TIME: "2023-09-07 22:53:15",
      SENDER_NAME: "Rahul Bhuyan",
      SENDER_MOBILE: "+91-9859777951",
      SENDER_EMAIL: "newcreative2013@gmail.com",
      SUBJECT: "Requirement for Non Woven Bag",
      SENDER_COMPANY: "M Print",
      SENDER_ADDRESS:
        "Ground Floor House No 32 K R B Road Bharalumukh W/o Jagadish Ch Das Kamrup Metropolitan, Guwahati, Assam,         781009",
      SENDER_CITY: "Guwahati",
      SENDER_STATE: "Assam",
      SENDER_PINCODE: "781009",
      SENDER_COUNTRY_ISO: "IN",
      SENDER_MOBILE_ALT: "",
      SENDER_PHONE: "",
      SENDER_PHONE_ALT: "",
      SENDER_EMAIL_ALT: "",
      QUERY_PRODUCT_NAME: "Non Woven Bag",
      QUERY_MESSAGE:
        "I want to buy Non Woven Bag.\r\rKindly send me price and other details.<br>Size : 15*17 Inch<br>Bag Type : D Cut Bag<br>Quantity : 10000 Piece<br>Probable Order Value : Rs. 1 to 2 Lakh<br>Probable Requirement Type : Business Use<br>",
      QUERY_MCAT_NAME: "Non Woven Bag",
      CALL_DURATION: "",
      RECEIVER_MOBILE: "",
    },
    {
      UNIQUE_QUERY_ID: "697464933",
      QUERY_TYPE: "B",
      QUERY_TIME: "2023-09-07 22:53:33",
      SENDER_NAME: "Om Prakash",
      SENDER_MOBILE: "+91-8910987166",
      SENDER_EMAIL: "omprakashseth98@gmail.com",
      SUBJECT: "Requirement for Colored Non Woven Bag",
      SENDER_COMPANY: "Om Jindal Supplier",
      SENDER_ADDRESS: "Baidyabati, West Bengal",
      SENDER_CITY: "Baidyabati",
      SENDER_STATE: "West Bengal",
      SENDER_PINCODE: "",
      SENDER_COUNTRY_ISO: "IN",
      SENDER_MOBILE_ALT: "",
      SENDER_PHONE: "",
      SENDER_PHONE_ALT: "",
      SENDER_EMAIL_ALT: "",
      QUERY_PRODUCT_NAME: "Colored Non Woven Bag",
      QUERY_MESSAGE:
        "I want to buy Colored Non Woven Bag.\r\r\r\r\r\rKindly send me price and other details.<br>Bag Type : W Cut Bag<br>Quantity : 500 Kg<br>Type of Requirement : Monthly Order<br>Probable Order Value : Rs. 62,000 - 92,000<br>Probable Requirement Type : Business Use<br>",
      QUERY_MCAT_NAME: "Non Woven Bag",
      CALL_DURATION: "",
      RECEIVER_MOBILE: "",
    },
    {
      UNIQUE_QUERY_ID: "697464953",
      QUERY_TYPE: "B",
      QUERY_TIME: "2023-09-07 22:53:44",
      SENDER_NAME: "Jatinder",
      SENDER_MOBILE: "+91-9056699600",
      SENDER_EMAIL: "katariasagar24@gmail.com",
      SUBJECT: "Requirement for Non Woven Carry Bag in Delhi",
      SENDER_COMPANY: "G.K Plastic",
      SENDER_ADDRESS:
        "Jassian Road, Badi Haibowal,Street Number 1,Ludhiana, Ludhiana, Punjab,         141001",
      SENDER_CITY: "Ludhiana",
      SENDER_STATE: "Punjab",
      SENDER_PINCODE: "141001",
      SENDER_COUNTRY_ISO: "IN",
      SENDER_MOBILE_ALT: "+91-9517751802",
      SENDER_PHONE: "",
      SENDER_PHONE_ALT: "",
      SENDER_EMAIL_ALT: "",
      QUERY_PRODUCT_NAME: "Non Woven Carry Bag in Delhi",
      QUERY_MESSAGE:
        "My Requirement is for Non Woven Carry Bag in Delhi. Kindly send me price and other details.<br>Bag Type : D Cut Bag<br>Quantity : 1000 Kg<br>Type of Requirement : Sample Requirement<br>Probable Order Value : Rs. 1,25,000 - 1,85,000<br>Probable Requirement Type : Business Use<br>",
      QUERY_MCAT_NAME: "Non Woven Bag",
      CALL_DURATION: "",
      RECEIVER_MOBILE: "",
    },
    {
      UNIQUE_QUERY_ID: "2544369728",
      QUERY_TYPE: "W",
      QUERY_TIME: "2023-09-07 23:33:23",
      SENDER_NAME: "Manish Kumar",
      SENDER_MOBILE: "+91-9817063736",
      SENDER_EMAIL: "",
      SUBJECT: "Requirement for PP Woven Carry Bag W Cut 20 X 26",
      SENDER_COMPANY: "",
      SENDER_ADDRESS: "Kullu, Himachal Pradesh",
      SENDER_CITY: "Kullu",
      SENDER_STATE: "Himachal Pradesh",
      SENDER_PINCODE: "",
      SENDER_COUNTRY_ISO: "IN",
      SENDER_MOBILE_ALT: "+91-9882863736",
      SENDER_PHONE: "",
      SENDER_PHONE_ALT: "",
      SENDER_EMAIL_ALT: "",
      QUERY_PRODUCT_NAME: "PP Woven Carry Bag W Cut 20 X 26",
      QUERY_MESSAGE:
        "I want to buy PP Woven Carry Bag W Cut 20 X 26. Kindly send me price and other details.<br>Storage Capacity : 15 KG<br>Usage/Application : Shopping<br>Probable Requirement Type : Business Use<br>",
      QUERY_MCAT_NAME: "Non Woven W Cut Bags",
      CALL_DURATION: "",
      RECEIVER_MOBILE: "",
    },
    {
      UNIQUE_QUERY_ID: "697789900",
      QUERY_TYPE: "B",
      QUERY_TIME: "2023-09-08 13:40:46",
      SENDER_NAME: "Altaf",
      SENDER_MOBILE: "+91-7709860686",
      SENDER_EMAIL: "",
      SUBJECT: "Requirement for D Cut Non Woven Bags",
      SENDER_COMPANY: "Altaf Designers",
      SENDER_ADDRESS: "Akluj, Maharashtra",
      SENDER_CITY: "Akluj",
      SENDER_STATE: "Maharashtra",
      SENDER_PINCODE: "",
      SENDER_COUNTRY_ISO: "IN",
      SENDER_MOBILE_ALT: "",
      SENDER_PHONE: "",
      SENDER_PHONE_ALT: "",
      SENDER_EMAIL_ALT: "",
      QUERY_PRODUCT_NAME: "D Cut Non Woven Bags",
      QUERY_MESSAGE:
        "I want to buy D Cut Non Woven Bags.\r\rKindly send me price and other details.<br>Quantity : 10000 Kg<br>Supplier Location : Pune, Kolhapur<br>Type of Requirement : Monthly<br>Probable Order Value : Rs. 12,50,000 - 17,50,000<br>Probable Requirement Type : Business Use<br>",
      QUERY_MCAT_NAME: "D-Cut Non Woven Bags",
      CALL_DURATION: "",
      RECEIVER_MOBILE: "",
    },
    {
      UNIQUE_QUERY_ID: "697789961",
      QUERY_TYPE: "B",
      QUERY_TIME: "2023-09-08 13:40:53",
      SENDER_NAME: "Anuradha Gupta",
      SENDER_MOBILE: "+91-7982310730",
      SENDER_EMAIL: "sceptre.medicals@gmail.com",
      SUBJECT: "Requirement for Non Woven Fabric Bags",
      SENDER_COMPANY: "Sceptre Medical India Private Limited",
      SENDER_ADDRESS:
        "No. 14, First Floor, Community Centre Central Market, Ashok Vihar, Phase 1, Delhi, Delhi,         110052",
      SENDER_CITY: "Delhi",
      SENDER_STATE: "Delhi",
      SENDER_PINCODE: "110052",
      SENDER_COUNTRY_ISO: "IN",
      SENDER_MOBILE_ALT: "+91-8506077757",
      SENDER_PHONE: "+(91)-(11)-45067231",
      SENDER_PHONE_ALT: "",
      SENDER_EMAIL_ALT: "support@sceptremedical.com",
      QUERY_PRODUCT_NAME: "Non Woven Fabric Bags",
      QUERY_MESSAGE:
        "I want to buy Non Woven Fabric Bags Manufacturer In Delhi.<br>Quantity : 5000 Kg<br>Type of Requirement : Quarterly Order<br>Probable Order Value : Rs. 6,25,000 - 9,25,000<br>Probable Requirement Type : Business Use<br>",
      QUERY_MCAT_NAME: "Non Woven Bag",
      CALL_DURATION: "",
      RECEIVER_MOBILE: "",
    },
    {
      UNIQUE_QUERY_ID: "697790010",
      QUERY_TYPE: "B",
      QUERY_TIME: "2023-09-08 13:41:01",
      SENDER_NAME: "Siddharth Veer Singhal",
      SENDER_MOBILE: "+91-9458201233",
      SENDER_EMAIL: "siddharthaveer@gmail.com",
      SUBJECT: "Requirement for Non Woven Fab",
      SENDER_COMPANY: "Ved Enterprises",
      SENDER_ADDRESS:
        "30,MAYUR VIHAR,MEERUT, Meerut, Uttar Pradesh,         250004",
      SENDER_CITY: "Meerut",
      SENDER_STATE: "Uttar Pradesh",
      SENDER_PINCODE: "250004",
      SENDER_COUNTRY_ISO: "IN",
      SENDER_MOBILE_ALT: "+91-9149080752",
      SENDER_PHONE: "",
      SENDER_PHONE_ALT: "",
      SENDER_EMAIL_ALT: "",
      QUERY_PRODUCT_NAME: "Non Woven Fab",
      QUERY_MESSAGE:
        "I want to buy Non Woven Fab.\r\r\r\r\r\rI need only manufacturers details.\r\rKindly send me price and other details.<br>Quantity : 3000-4000 Kg<br>Type of Requirement : Monthly<br>Probable Order Value : Rs. 3,85,000 - 5,25,000<br>Why do you need this : For Reselling<br>",
      QUERY_MCAT_NAME: "Non Woven Fabric",
      CALL_DURATION: "",
      RECEIVER_MOBILE: "",
    },
    {
      UNIQUE_QUERY_ID: "697790082",
      QUERY_TYPE: "B",
      QUERY_TIME: "2023-09-08 13:41:10",
      SENDER_NAME: "Vikas Sharma",
      SENDER_MOBILE: "+91-7807677485",
      SENDER_EMAIL: "vs16128415@gmail.com",
      SUBJECT: "Requirement for Nonwovens Fabrics",
      SENDER_COMPANY: "",
      SENDER_ADDRESS: "Rohru, Himachal Pradesh",
      SENDER_CITY: "Rohru",
      SENDER_STATE: "Himachal Pradesh",
      SENDER_PINCODE: "",
      SENDER_COUNTRY_ISO: "IN",
      SENDER_MOBILE_ALT: "",
      SENDER_PHONE: "",
      SENDER_PHONE_ALT: "",
      SENDER_EMAIL_ALT: "",
      QUERY_PRODUCT_NAME: "Nonwovens Fabrics",
      QUERY_MESSAGE:
        "I am interested in buying Nonwovens Fabrics. Kindly send me price and other details.<br>pattren : plain,print<br>Quantity : 500 Kg<br>Probable Order Value : Rs. 43,000 - 55,000<br>Probable Requirement Type : Business Use<br>",
      QUERY_MCAT_NAME: "Non Woven Fabric",
      CALL_DURATION: "",
      RECEIVER_MOBILE: "",
    },
    {
      UNIQUE_QUERY_ID: "97113703",
      QUERY_TYPE: "P",
      QUERY_TIME: "2023-09-08 13:49:50",
      SENDER_NAME: "Akash",
      SENDER_MOBILE: "+91-8408880069",
      SENDER_EMAIL: "",
      SUBJECT: "Buyer Call",
      SENDER_COMPANY: "Shoe Basket",
      SENDER_ADDRESS: "Goa, Goa",
      SENDER_CITY: "Goa",
      SENDER_STATE: "Goa",
      SENDER_PINCODE: "",
      SENDER_COUNTRY_ISO: "IN",
      SENDER_MOBILE_ALT: "",
      SENDER_PHONE: "",
      SENDER_PHONE_ALT: "",
      SENDER_EMAIL_ALT: "",
      QUERY_PRODUCT_NAME: "Non Woven For Footwear Packaging",
      QUERY_MESSAGE: "",
      QUERY_MCAT_NAME: "Non Woven Shoes Bag",
      CALL_DURATION: "23",
      RECEIVER_MOBILE: "9253186178",
    },
    {
      UNIQUE_QUERY_ID: "97118608",
      QUERY_TYPE: "P",
      QUERY_TIME: "2023-09-08 13:56:19",
      SENDER_NAME: "Vikas Sharma",
      SENDER_MOBILE: "+91-7807677485",
      SENDER_EMAIL: "vs16128415@gmail.com",
      SUBJECT: "Buyer Call",
      SENDER_COMPANY: "",
      SENDER_ADDRESS: "Rohru, Himachal Pradesh",
      SENDER_CITY: "Rohru",
      SENDER_STATE: "Himachal Pradesh",
      SENDER_PINCODE: "",
      SENDER_COUNTRY_ISO: "IN",
      SENDER_MOBILE_ALT: "",
      SENDER_PHONE: "",
      SENDER_PHONE_ALT: "",
      SENDER_EMAIL_ALT: "",
      QUERY_PRODUCT_NAME: "",
      QUERY_MESSAGE: "",
      QUERY_MCAT_NAME: "",
      CALL_DURATION: "48",
      RECEIVER_MOBILE: "9667316033",
    },
    {
      UNIQUE_QUERY_ID: "97157351",
      QUERY_TYPE: "P",
      QUERY_TIME: "2023-09-08 14:47:35",
      SENDER_NAME: "Moshil Khan",
      SENDER_MOBILE: "+91-9917733455",
      SENDER_EMAIL: "",
      SUBJECT: "Buyer Call",
      SENDER_COMPANY: "KHAN CARRY BAG",
      SENDER_ADDRESS: "Moradabad, Uttar Pradesh",
      SENDER_CITY: "Moradabad",
      SENDER_STATE: "Uttar Pradesh",
      SENDER_PINCODE: "",
      SENDER_COUNTRY_ISO: "IN",
      SENDER_MOBILE_ALT: "",
      SENDER_PHONE: "",
      SENDER_PHONE_ALT: "",
      SENDER_EMAIL_ALT: "",
      QUERY_PRODUCT_NAME: "",
      QUERY_MESSAGE: "",
      QUERY_MCAT_NAME: "",
      CALL_DURATION: "24",
      RECEIVER_MOBILE: "9253186178",
    },
    {
      UNIQUE_QUERY_ID: "697965189",
      QUERY_TYPE: "B",
      QUERY_TIME: "2023-09-08 22:04:59",
      SENDER_NAME: "Gitesh Sharma",
      SENDER_MOBILE: "+91-9718506712",
      SENDER_EMAIL: "deepaarthenterprises@gmail.com",
      SUBJECT: "Requirement for White Plain Non Woven Fabric",
      SENDER_COMPANY: "Jak Group Private Limited",
      SENDER_ADDRESS: "Gurugram, Haryana",
      SENDER_CITY: "Gurugram",
      SENDER_STATE: "Haryana",
      SENDER_PINCODE: "",
      SENDER_COUNTRY_ISO: "IN",
      SENDER_MOBILE_ALT: "+91-7011638401",
      SENDER_PHONE: "",
      SENDER_PHONE_ALT: "",
      SENDER_EMAIL_ALT: "gitesh83@gmail.com",
      QUERY_PRODUCT_NAME: "White Plain Non Woven Fabric",
      QUERY_MESSAGE:
        "I want to buy White 63-128 Inch Plain Non Woven Fabric, GSM: 20-150.Kindly send me price and other details.<br>Quantity : 500 Kg<br>Type of Requirement : Monthly<br>Probable Order Value : Rs. 52,000 - 71,000<br>Probable Requirement Type : Business Use<br>",
      QUERY_MCAT_NAME: "Non Woven Cloth",
      CALL_DURATION: "",
      RECEIVER_MOBILE: "",
    },
    {
      UNIQUE_QUERY_ID: "697965275",
      QUERY_TYPE: "B",
      QUERY_TIME: "2023-09-08 22:05:33",
      SENDER_NAME: "Kapil Singla",
      SENDER_MOBILE: "+91-9315620525",
      SENDER_EMAIL: "",
      SUBJECT: "Requirement for Agriculture Non Woven Fabric",
      SENDER_COMPANY: "",
      SENDER_ADDRESS: "Panipat, Haryana",
      SENDER_CITY: "Panipat",
      SENDER_STATE: "Haryana",
      SENDER_PINCODE: "",
      SENDER_COUNTRY_ISO: "IN",
      SENDER_MOBILE_ALT: "",
      SENDER_PHONE: "",
      SENDER_PHONE_ALT: "",
      SENDER_EMAIL_ALT: "",
      QUERY_PRODUCT_NAME: "Agriculture Non Woven Fabric",
      QUERY_MESSAGE:
        "I want to buy Agriculture Non Woven Fabric.Kindly send me price and other details.<br>Quantity : 5000 Kg<br>Type of Requirement : Monthly<br>Probable Order Value : Rs. 5,50,000 - 7,50,000<br>Why do you need this : For Business Use<br>",
      QUERY_MCAT_NAME: "Non Woven Fabric",
      CALL_DURATION: "",
      RECEIVER_MOBILE: "",
    },
    {
      UNIQUE_QUERY_ID: "697965309",
      QUERY_TYPE: "B",
      QUERY_TIME: "2023-09-08 22:05:46",
      SENDER_NAME: "Yatin Malik",
      SENDER_MOBILE: "+91-7404981370",
      SENDER_EMAIL: "samtrading007@gmail.com",
      SUBJECT: "Requirement for Non Woven Printed Fabric",
      SENDER_COMPANY: "SAM Trading Company",
      SENDER_ADDRESS:
        "1379, 2nd Floor, Sector 13-17 Huda, Panipat, Haryana,         132103",
      SENDER_CITY: "Panipat",
      SENDER_STATE: "Haryana",
      SENDER_PINCODE: "132103",
      SENDER_COUNTRY_ISO: "IN",
      SENDER_MOBILE_ALT: "+91-9729304180",
      SENDER_PHONE: "",
      SENDER_PHONE_ALT: "",
      SENDER_EMAIL_ALT: "",
      QUERY_PRODUCT_NAME: "Non Woven Printed Fabric",
      QUERY_MESSAGE:
        "I am interested in buying Non Woven Printed Fabric. Kindly send me price and other details.<br>Type : Cotton<br>Color : Multi color<br>Quantity : 500 Kg<br>Probable Order Value : Rs. 64,000 - 75,000<br>Probable Requirement Type : Business Use<br>",
      QUERY_MCAT_NAME: "Non Woven Printed Fabric",
      CALL_DURATION: "",
      RECEIVER_MOBILE: "",
    },
    {
      UNIQUE_QUERY_ID: "2545588107",
      QUERY_TYPE: "W",
      QUERY_TIME: "2023-09-09 11:49:46",
      SENDER_NAME: "Anupma Bindra",
      SENDER_MOBILE: "+91-9810194101",
      SENDER_EMAIL: "anupma.bindra@gmail.com",
      SUBJECT: "Requirement for U Cut Non Woven Bags",
      SENDER_COMPANY: "Viacom18",
      SENDER_ADDRESS: "Gurgaon, Haryana",
      SENDER_CITY: "Gurgaon",
      SENDER_STATE: "Haryana",
      SENDER_PINCODE: "",
      SENDER_COUNTRY_ISO: "IN",
      SENDER_MOBILE_ALT: "",
      SENDER_PHONE: "",
      SENDER_PHONE_ALT: "",
      SENDER_EMAIL_ALT: "",
      QUERY_PRODUCT_NAME: "U Cut Non Woven Bags",
      QUERY_MESSAGE: "I am interested in U Cut Non Woven Bags<br>",
      QUERY_MCAT_NAME: "Non Woven U Cut Bag",
      CALL_DURATION: "",
      RECEIVER_MOBILE: "",
    },
    {
      UNIQUE_QUERY_ID: "698393288",
      QUERY_TYPE: "B",
      QUERY_TIME: "2023-09-09 16:24:51",
      SENDER_NAME: "Samant Naran",
      SENDER_MOBILE: "+91-9650794688",
      SENDER_EMAIL: "sushil533@gmail.com",
      SUBJECT: "Requirement for Bag Fabric",
      SENDER_COMPANY: "Prostar",
      SENDER_ADDRESS:
        "Bs 12k, 1st Floor, Malibu Town, Sona Road, Delhi, Delhi,         110017",
      SENDER_CITY: "Delhi",
      SENDER_STATE: "Delhi",
      SENDER_PINCODE: "110017",
      SENDER_COUNTRY_ISO: "IN",
      SENDER_MOBILE_ALT: "",
      SENDER_PHONE: "",
      SENDER_PHONE_ALT: "",
      SENDER_EMAIL_ALT: "",
      QUERY_PRODUCT_NAME: "Bag Fabric",
      QUERY_MESSAGE:
        "I want to purchase Bag Fabric. Kindly send me price and other details.<br>Probable Requirement Type : Business Use<br>",
      QUERY_MCAT_NAME: "Bag Fabric",
      CALL_DURATION: "",
      RECEIVER_MOBILE: "",
    },
    {
      UNIQUE_QUERY_ID: "698478142",
      QUERY_TYPE: "B",
      QUERY_TIME: "2023-09-09 19:13:02",
      SENDER_NAME: "Mukesh",
      SENDER_MOBILE: "+91-9044963676",
      SENDER_EMAIL: "monu_200000@yahoo.in",
      SUBJECT: "Requirement for Non Woven Fabrics",
      SENDER_COMPANY: "",
      SENDER_ADDRESS: "Kanpur, Uttar Pradesh",
      SENDER_CITY: "Kanpur",
      SENDER_STATE: "Uttar Pradesh",
      SENDER_PINCODE: "",
      SENDER_COUNTRY_ISO: "IN",
      SENDER_MOBILE_ALT: "",
      SENDER_PHONE: "",
      SENDER_PHONE_ALT: "",
      SENDER_EMAIL_ALT: "",
      QUERY_PRODUCT_NAME: "Non Woven Fabrics",
      QUERY_MESSAGE:
        "My Requirement is for Non Woven Fabrics. Kindly send me price and other details.<br>Color : Multiple<br>Quantity : 250 Kg<br>Prints/Pattern : Plain/Solids<br>Probable Order Value : Rs. 25,000 - 28,000<br>Probable Requirement Type : Business Use<br>",
      QUERY_MCAT_NAME: "Non Woven Fabric",
      CALL_DURATION: "",
      RECEIVER_MOBILE: "",
    },
    {
      UNIQUE_QUERY_ID: "698478176",
      QUERY_TYPE: "B",
      QUERY_TIME: "2023-09-09 19:13:07",
      SENDER_NAME: "Jhalaram Karmta",
      SENDER_MOBILE: "+91-9945918423",
      SENDER_EMAIL: "jhalaramdesai@gmail.com",
      SUBJECT: "Requirement for Non Woven W Cut Bags",
      SENDER_COMPANY: "Ramdev Plastics",
      SENDER_ADDRESS:
        "Market Road, Near Indian Sweet Stall, Hoskote, Hoskote, Karnataka,         562114",
      SENDER_CITY: "Hoskote",
      SENDER_STATE: "Karnataka",
      SENDER_PINCODE: "562114",
      SENDER_COUNTRY_ISO: "IN",
      SENDER_MOBILE_ALT: "",
      SENDER_PHONE: "",
      SENDER_PHONE_ALT: "",
      SENDER_EMAIL_ALT: "",
      QUERY_PRODUCT_NAME: "Non Woven W Cut Bags",
      QUERY_MESSAGE:
        "My Requirement is for Non Woven W Cut Bags. Kindly send me price and other details.<br>Bag Type : W Cut Bag<br>Capacity(In KG) : 1 Kg<br>Probable Requirement Type : Business Use<br>",
      QUERY_MCAT_NAME: "Non Woven W Cut Bags",
      CALL_DURATION: "",
      RECEIVER_MOBILE: "",
    },
    {
      UNIQUE_QUERY_ID: "698478317",
      QUERY_TYPE: "B",
      QUERY_TIME: "2023-09-09 19:13:26",
      SENDER_NAME: "Saurabh",
      SENDER_MOBILE: "+91-8591996318",
      SENDER_EMAIL: "sales3@advancebioplast.com",
      SUBJECT: "Requirement for D-Cut Non Woven Bags",
      SENDER_COMPANY: "Adnvace Bio Materials",
      SENDER_ADDRESS: "Bankura, West Bengal",
      SENDER_CITY: "Bankura",
      SENDER_STATE: "West Bengal",
      SENDER_PINCODE: "",
      SENDER_COUNTRY_ISO: "IN",
      SENDER_MOBILE_ALT: "",
      SENDER_PHONE: "",
      SENDER_PHONE_ALT: "",
      SENDER_EMAIL_ALT: "",
      QUERY_PRODUCT_NAME: "D-Cut Non Woven Bags",
      QUERY_MESSAGE:
        "I want to buy D-Cut Non Woven Bags.\r\rKindly send me price and other details.<br>Probable Requirement Type : Business Use<br>",
      QUERY_MCAT_NAME: "D-Cut Non Woven Bags",
      CALL_DURATION: "",
      RECEIVER_MOBILE: "",
    },
    {
      UNIQUE_QUERY_ID: "698479860",
      QUERY_TYPE: "B",
      QUERY_TIME: "2023-09-09 19:17:28",
      SENDER_NAME: "Aalok",
      SENDER_MOBILE: "+91-8808231341",
      SENDER_EMAIL: "",
      SUBJECT: "Requirement for Non Woven Box Bag",
      SENDER_COMPANY: "Maa Printing Press",
      SENDER_ADDRESS: "Ambedkar Nagar, Uttar Pradesh",
      SENDER_CITY: "Ambedkar Nagar",
      SENDER_STATE: "Uttar Pradesh",
      SENDER_PINCODE: "",
      SENDER_COUNTRY_ISO: "IN",
      SENDER_MOBILE_ALT: "",
      SENDER_PHONE: "",
      SENDER_PHONE_ALT: "",
      SENDER_EMAIL_ALT: "",
      QUERY_PRODUCT_NAME: "Non Woven Box Bag",
      QUERY_MESSAGE:
        "I want to buy Non Woven Box Bag.\r\rKindly send me price and other details.<br>Bag Type : D Cut Bag<br>Quantity Required : 3 Ton<br>Type of Requirement : Monthly Order<br>Probable Requirement Type : Business Use<br>",
      QUERY_MCAT_NAME: "Non Woven Bag",
      CALL_DURATION: "",
      RECEIVER_MOBILE: "",
    },
    {
      UNIQUE_QUERY_ID: "698515730",
      QUERY_TYPE: "B",
      QUERY_TIME: "2023-09-09 21:04:51",
      SENDER_NAME: "Praveena",
      SENDER_MOBILE: "+91-9418663727",
      SENDER_EMAIL: "",
      SUBJECT: "Requirement for Non Woven Bag Raw Material",
      SENDER_COMPANY: "Pushkar Enterprises",
      SENDER_ADDRESS:
        "-,SHYAM NIWAS, VILLAGE AGWAHI PO SHOGHI,AGWAHI SHOGHI SHIMLA, Shoghi, Himachal Pradesh,         171219",
      SENDER_CITY: "Shoghi",
      SENDER_STATE: "Himachal Pradesh",
      SENDER_PINCODE: "171219",
      SENDER_COUNTRY_ISO: "IN",
      SENDER_MOBILE_ALT: "",
      SENDER_PHONE: "",
      SENDER_PHONE_ALT: "",
      SENDER_EMAIL_ALT: "",
      QUERY_PRODUCT_NAME: "Non Woven Bag Raw Material",
      QUERY_MESSAGE:
        "I am interested in buying Non Woven Bag Raw Material. Kindly send me price and other details.<br>GSM : 80 Gsm<br>Color : Yellow , Orange Etc<br>Quantity : 500 Kg<br>Probable Order Value : Rs. 50,000 - 55,000<br>Probable Requirement Type : Business Use<br>",
      QUERY_MCAT_NAME: "Non Woven Fabric",
      CALL_DURATION: "",
      RECEIVER_MOBILE: "",
    },
    {
      UNIQUE_QUERY_ID: "698515856",
      QUERY_TYPE: "B",
      QUERY_TIME: "2023-09-09 21:05:16",
      SENDER_NAME: "Jeevan Kumar",
      SENDER_MOBILE: "+91-7888652722",
      SENDER_EMAIL: "jeevansalhotra16194@gmail.com",
      SUBJECT: "Requirement for D-cut Non Woven Bags",
      SENDER_COMPANY: "",
      SENDER_ADDRESS: "Pathankot, Punjab",
      SENDER_CITY: "Pathankot",
      SENDER_STATE: "Punjab",
      SENDER_PINCODE: "",
      SENDER_COUNTRY_ISO: "IN",
      SENDER_MOBILE_ALT: "",
      SENDER_PHONE: "",
      SENDER_PHONE_ALT: "",
      SENDER_EMAIL_ALT: "",
      QUERY_PRODUCT_NAME: "D-cut Non Woven Bags",
      QUERY_MESSAGE:
        "I want to buy D-cut Non Woven Bags.\r\rKindly send me price and other details.<br>Probable Requirement Type : Business Use<br>",
      QUERY_MCAT_NAME: "D-Cut Non Woven Bags",
      CALL_DURATION: "",
      RECEIVER_MOBILE: "",
    },
    {
      UNIQUE_QUERY_ID: "698516055",
      QUERY_TYPE: "B",
      QUERY_TIME: "2023-09-09 21:05:49",
      SENDER_NAME: "Pankaj Wadhwani",
      SENDER_MOBILE: "+91-7067190900",
      SENDER_EMAIL: "pwadhwani121@gmail.com",
      SUBJECT: "Requirement for 16 X 20 Inch Non Woven Bag",
      SENDER_COMPANY: "Pankaj Bag Dhmtari",
      SENDER_ADDRESS: "Dhamtari, Chhattisgarh",
      SENDER_CITY: "Dhamtari",
      SENDER_STATE: "Chhattisgarh",
      SENDER_PINCODE: "",
      SENDER_COUNTRY_ISO: "IN",
      SENDER_MOBILE_ALT: "",
      SENDER_PHONE: "",
      SENDER_PHONE_ALT: "",
      SENDER_EMAIL_ALT: "",
      QUERY_PRODUCT_NAME: "16 X 20 Inch Non Woven Bag",
      QUERY_MESSAGE:
        "I am interested in buying 16 X 20 Inch Non Woven Bag. Kindly send me price and other details.<br>Capacity : 8 Kg<br>Material : Non Woven<br>Probable Requirement Type : Business Use<br>",
      QUERY_MCAT_NAME: "Non Woven Bag",
      CALL_DURATION: "",
      RECEIVER_MOBILE: "",
    },
    {
      UNIQUE_QUERY_ID: "698516380",
      QUERY_TYPE: "B",
      QUERY_TIME: "2023-09-09 21:06:48",
      SENDER_NAME: "Ashik",
      SENDER_MOBILE: "+91-7005053660",
      SENDER_EMAIL: "mdashiqueelahi10@gmail.com",
      SUBJECT: "Requirement for D Cut Plain or Coloured Non Woven Bags",
      SENDER_COMPANY: "AR Enterprises",
      SENDER_ADDRESS: "Imphal, Manipur",
      SENDER_CITY: "Imphal",
      SENDER_STATE: "Manipur",
      SENDER_PINCODE: "",
      SENDER_COUNTRY_ISO: "IN",
      SENDER_MOBILE_ALT: "",
      SENDER_PHONE: "",
      SENDER_PHONE_ALT: "",
      SENDER_EMAIL_ALT: "",
      QUERY_PRODUCT_NAME: "D Cut Plain or Coloured Non Woven Bags",
      QUERY_MESSAGE:
        "I am interested in buying D Cut Plain or Coloured Non Woven Bags. Kindly send me price and other details.<br>Probable Requirement Type : Business Use<br>",
      QUERY_MCAT_NAME: "D-Cut Non Woven Bags",
      CALL_DURATION: "",
      RECEIVER_MOBILE: "",
    },
    {
      UNIQUE_QUERY_ID: "2546162289",
      QUERY_TYPE: "W",
      QUERY_TIME: "2023-09-09 21:17:22",
      SENDER_NAME: "HARIKRISHNA Pilli",
      SENDER_MOBILE: "+91-6304124973",
      SENDER_EMAIL: "",
      SUBJECT: "Requirement for 5 Kg Loop Handle Non Woven Bag",
      SENDER_COMPANY: "",
      SENDER_ADDRESS: "Rajampet, Andhra Pradesh",
      SENDER_CITY: "Rajampet",
      SENDER_STATE: "Andhra Pradesh",
      SENDER_PINCODE: "",
      SENDER_COUNTRY_ISO: "IN",
      SENDER_MOBILE_ALT: "",
      SENDER_PHONE: "",
      SENDER_PHONE_ALT: "",
      SENDER_EMAIL_ALT: "",
      QUERY_PRODUCT_NAME: "5 Kg Loop Handle Non Woven Bag",
      QUERY_MESSAGE:
        "I want to buy 5 Kg Loop Handle Non Woven Bag. Kindly send me price and other details.<br>Bag Type : Loop Handle Bag<br>Capacity : 5 Kg<br>Quantity : 500<br>Quantity Unit : Piece<br>Probable Order Value : Rs. 6,800 - 8,200<br>Probable Requirement Type : Business Use<br>",
      QUERY_MCAT_NAME: "Loop Handle Non Woven Bag",
      CALL_DURATION: "",
      RECEIVER_MOBILE: "",
    },
    {
      UNIQUE_QUERY_ID: "2546605895",
      QUERY_TYPE: "W",
      QUERY_TIME: "2023-09-10 13:41:57",
      SENDER_NAME: "Laxmi Narayan",
      SENDER_MOBILE: "+91-8930062621",
      SENDER_EMAIL: "",
      SUBJECT: "Requirement for School Bag Fabric",
      SENDER_COMPANY: "Himanshi Shop",
      SENDER_ADDRESS: "Palwal, Haryana",
      SENDER_CITY: "Palwal",
      SENDER_STATE: "Haryana",
      SENDER_PINCODE: "",
      SENDER_COUNTRY_ISO: "IN",
      SENDER_MOBILE_ALT: "",
      SENDER_PHONE: "",
      SENDER_PHONE_ALT: "",
      SENDER_EMAIL_ALT: "",
      QUERY_PRODUCT_NAME: "School Bag Fabric",
      QUERY_MESSAGE:
        "I want to buy School Bag Fabric.\r\rI will need the samples first.\r\rKindly send me price and other details.<br>Quantity : 1<br>Quantity Unit : Kg<br>Type of Requirement : Monthly<br>Probable Order Value : Rs. 90 - 100<br>Probable Requirement Type : Business Use<br>",
      QUERY_MCAT_NAME: "Bag Fabric",
      CALL_DURATION: "",
      RECEIVER_MOBILE: "",
    },
    {
      UNIQUE_QUERY_ID: "699085054",
      QUERY_TYPE: "B",
      QUERY_TIME: "2023-09-10 22:40:23",
      SENDER_NAME: "Pijush Kanti Sarkar",
      SENDER_MOBILE: "+91-6295988742",
      SENDER_EMAIL: "sarkarpijush850@gmail.com",
      SUBJECT: "Requirement for PP Spunbond Nonwoven Fabric",
      SENDER_COMPANY: "Sarkar Enterprise",
      SENDER_ADDRESS:
        "33/3,CHANDMARI ROAD EAST,BARRACKPORE, Kolkata, West Bengal,         700122",
      SENDER_CITY: "Kolkata",
      SENDER_STATE: "West Bengal",
      SENDER_PINCODE: "700122",
      SENDER_COUNTRY_ISO: "IN",
      SENDER_MOBILE_ALT: "",
      SENDER_PHONE: "",
      SENDER_PHONE_ALT: "",
      SENDER_EMAIL_ALT: "",
      QUERY_PRODUCT_NAME: "PP Spunbond Nonwoven Fabric",
      QUERY_MESSAGE:
        "Pp Spunbond Nonwoven Fabric<br>GSM : 8 Gsm to 300 GSM<br>Material : Polypropylene(PP)<br>Quantity : 1000 Kg<br>Probable Order Value : Rs. 1,44,000 - 1,45,000<br>Probable Requirement Type : Business Use<br>",
      QUERY_MCAT_NAME: "PP Spunbond Nonwoven Fabric",
      CALL_DURATION: "",
      RECEIVER_MOBILE: "",
    },
    {
      UNIQUE_QUERY_ID: "699085076",
      QUERY_TYPE: "B",
      QUERY_TIME: "2023-09-10 22:40:34",
      SENDER_NAME: "VIJAY KRISHAN AGRAWAL",
      SENDER_MOBILE: "+91-7644843304",
      SENDER_EMAIL: "nileshagarwal38@gmail.com",
      SUBJECT: "Requirement for Non Woven D Cut Bag",
      SENDER_COMPANY: "Aggarwal Electronics",
      SENDER_ADDRESS: "Darbhanga, Bihar",
      SENDER_CITY: "Darbhanga",
      SENDER_STATE: "Bihar",
      SENDER_PINCODE: "",
      SENDER_COUNTRY_ISO: "IN",
      SENDER_MOBILE_ALT: "",
      SENDER_PHONE: "",
      SENDER_PHONE_ALT: "",
      SENDER_EMAIL_ALT: "nileshagrawal38@gmail.com",
      QUERY_PRODUCT_NAME: "Non Woven D Cut Bag",
      QUERY_MESSAGE:
        "I am interested in Non Woven D Cut BagKindly send me price and other details.<br>Capacity : All Sizes<br>Usage/Application : Shopping<br>Probable Requirement Type : Business Use<br>",
      QUERY_MCAT_NAME: "D-Cut Non Woven Bags",
      CALL_DURATION: "",
      RECEIVER_MOBILE: "",
    },
    {
      UNIQUE_QUERY_ID: "699085135",
      QUERY_TYPE: "B",
      QUERY_TIME: "2023-09-10 22:41:02",
      SENDER_NAME: "Rajesh",
      SENDER_MOBILE: "+91-7979971020",
      SENDER_EMAIL: "mimansa815@gmail.com",
      SUBJECT: "Requirement for Non Woven Carry Bag W- Cut",
      SENDER_COMPANY: "Gyan Sagar",
      SENDER_ADDRESS: "Bokaro Steel City, Jharkhand",
      SENDER_CITY: "Bokaro Steel City",
      SENDER_STATE: "Jharkhand",
      SENDER_PINCODE: "",
      SENDER_COUNTRY_ISO: "IN",
      SENDER_MOBILE_ALT: "",
      SENDER_PHONE: "",
      SENDER_PHONE_ALT: "",
      SENDER_EMAIL_ALT: "",
      QUERY_PRODUCT_NAME: "Non Woven Carry Bag W- Cut",
      QUERY_MESSAGE:
        "I want to buy Non Woven Carry Bag W- Cut. Kindly send me price and other details.<br>Color : White<br>Features : Virgin quality product at the best price<br>Probable Requirement Type : Business Use<br>",
      QUERY_MCAT_NAME: "Non Woven W Cut Bags",
      CALL_DURATION: "",
      RECEIVER_MOBILE: "",
    },
    {
      UNIQUE_QUERY_ID: "699085155",
      QUERY_TYPE: "B",
      QUERY_TIME: "2023-09-10 22:41:11",
      SENDER_NAME: "Sandeep Jain",
      SENDER_MOBILE: "+91-9893875113",
      SENDER_EMAIL: "sj885799@gmail.com",
      SUBJECT: "Requirement for Non Woven D Cut Bag",
      SENDER_COMPANY: "Raj Tilak Traders / Sandeep Jain",
      SENDER_ADDRESS: "Indore, Madhya Pradesh",
      SENDER_CITY: "Indore",
      SENDER_STATE: "Madhya Pradesh",
      SENDER_PINCODE: "",
      SENDER_COUNTRY_ISO: "IN",
      SENDER_MOBILE_ALT: "",
      SENDER_PHONE: "",
      SENDER_PHONE_ALT: "",
      SENDER_EMAIL_ALT: "",
      QUERY_PRODUCT_NAME: "Non Woven D Cut Bag",
      QUERY_MESSAGE:
        "I want to buy Non Woven D Cut Bag. Kindly send me price and other details.<br>Capacity : 5kg<br>Usage/ Application : Shopping<br>Probable Requirement Type : Business Use<br>",
      QUERY_MCAT_NAME: "D-Cut Non Woven Bags",
      CALL_DURATION: "",
      RECEIVER_MOBILE: "",
    },
    {
      UNIQUE_QUERY_ID: "699277977",
      QUERY_TYPE: "B",
      QUERY_TIME: "2023-09-11 08:24:58",
      SENDER_NAME: "ANKUSH",
      SENDER_MOBILE: "+91-7807312685",
      SENDER_EMAIL: "ankushkumar12685@gmail.com",
      SUBJECT: "Requirement for Non Woven W Cut Bags",
      SENDER_COMPANY: "",
      SENDER_ADDRESS: "Mandi, Himachal Pradesh,         175121",
      SENDER_CITY: "Mandi",
      SENDER_STATE: "Himachal Pradesh",
      SENDER_PINCODE: "175121",
      SENDER_COUNTRY_ISO: "IN",
      SENDER_MOBILE_ALT: "",
      SENDER_PHONE: "",
      SENDER_PHONE_ALT: "",
      SENDER_EMAIL_ALT: "",
      QUERY_PRODUCT_NAME: "Non Woven W Cut Bags",
      QUERY_MESSAGE:
        "I am interested in buying Non Woven W Cut Bags. Kindly send me price and other details.<br>Pattern : Plain<br>Usage/ Application : Grocery<br>Probable Requirement Type : Business Use<br>",
      QUERY_MCAT_NAME: "Non Woven W Cut Bags",
      CALL_DURATION: "",
      RECEIVER_MOBILE: "",
    },
    {
      UNIQUE_QUERY_ID: "2547493645",
      QUERY_TYPE: "W",
      QUERY_TIME: "2023-09-11 13:39:06",
      SENDER_NAME: "Shahil",
      SENDER_MOBILE: "+91-9633005777",
      SENDER_EMAIL: "",
      SUBJECT: "Requirement for Raffia W Cut Bag",
      SENDER_COMPANY: "Blue Moon Traders",
      SENDER_ADDRESS: "Kasaragod, Kerala",
      SENDER_CITY: "Kasaragod",
      SENDER_STATE: "Kerala",
      SENDER_PINCODE: "",
      SENDER_COUNTRY_ISO: "IN",
      SENDER_MOBILE_ALT: "",
      SENDER_PHONE: "",
      SENDER_PHONE_ALT: "",
      SENDER_EMAIL_ALT: "",
      QUERY_PRODUCT_NAME: "Raffia W Cut Bag",
      QUERY_MESSAGE:
        "My Requirement is for Raffia W Cut Bag. Kindly send me price and other details.<br>Capacity : pes<br>Material : Polypropylene<br>Probable Requirement Type : Business Use<br>",
      QUERY_MCAT_NAME: "Non Woven W Cut Bags",
      CALL_DURATION: "",
      RECEIVER_MOBILE: "",
    },
    {
      UNIQUE_QUERY_ID: "98719808",
      QUERY_TYPE: "P",
      QUERY_TIME: "2023-09-11 17:01:12",
      SENDER_NAME: "Furqan Ahmad",
      SENDER_MOBILE: "+91-9359364545",
      SENDER_EMAIL: "kohinoorfurqan@yahoo.com",
      SUBJECT: "Buyer Call",
      SENDER_COMPANY: "Kohinoor Enterprises",
      SENDER_ADDRESS:
        "Shop no.- 31/300, Collectorate Road,  Agra  Saghir Fatima College, Agra, Uttar Pradesh,         282003",
      SENDER_CITY: "Agra",
      SENDER_STATE: "Uttar Pradesh",
      SENDER_PINCODE: "282003",
      SENDER_COUNTRY_ISO: "IN",
      SENDER_MOBILE_ALT: "+91-8923545861",
      SENDER_PHONE: "",
      SENDER_PHONE_ALT: "",
      SENDER_EMAIL_ALT: "",
      QUERY_PRODUCT_NAME: "",
      QUERY_MESSAGE: "",
      QUERY_MCAT_NAME: "",
      CALL_DURATION: "3",
      RECEIVER_MOBILE: "9253186178",
    },
    {
      UNIQUE_QUERY_ID: "98720052",
      QUERY_TYPE: "P",
      QUERY_TIME: "2023-09-11 17:01:31",
      SENDER_NAME: "Furqan Ahmad",
      SENDER_MOBILE: "+91-9359364545",
      SENDER_EMAIL: "kohinoorfurqan@yahoo.com",
      SUBJECT: "Buyer Call",
      SENDER_COMPANY: "Kohinoor Enterprises",
      SENDER_ADDRESS:
        "Shop no.- 31/300, Collectorate Road,  Agra  Saghir Fatima College, Agra, Uttar Pradesh,         282003",
      SENDER_CITY: "Agra",
      SENDER_STATE: "Uttar Pradesh",
      SENDER_PINCODE: "282003",
      SENDER_COUNTRY_ISO: "IN",
      SENDER_MOBILE_ALT: "+91-8923545861",
      SENDER_PHONE: "",
      SENDER_PHONE_ALT: "",
      SENDER_EMAIL_ALT: "",
      QUERY_PRODUCT_NAME: "",
      QUERY_MESSAGE: "",
      QUERY_MCAT_NAME: "",
      CALL_DURATION: "12",
      RECEIVER_MOBILE: "9253186178",
    },
    {
      UNIQUE_QUERY_ID: "98720414",
      QUERY_TYPE: "P",
      QUERY_TIME: "2023-09-11 17:01:57",
      SENDER_NAME: "Furqan Ahmad",
      SENDER_MOBILE: "+91-9359364545",
      SENDER_EMAIL: "kohinoorfurqan@yahoo.com",
      SUBJECT: "Buyer Call",
      SENDER_COMPANY: "Kohinoor Enterprises",
      SENDER_ADDRESS:
        "Shop no.- 31/300, Collectorate Road,  Agra  Saghir Fatima College, Agra, Uttar Pradesh,         282003",
      SENDER_CITY: "Agra",
      SENDER_STATE: "Uttar Pradesh",
      SENDER_PINCODE: "282003",
      SENDER_COUNTRY_ISO: "IN",
      SENDER_MOBILE_ALT: "+91-8923545861",
      SENDER_PHONE: "",
      SENDER_PHONE_ALT: "",
      SENDER_EMAIL_ALT: "",
      QUERY_PRODUCT_NAME: "",
      QUERY_MESSAGE: "",
      QUERY_MCAT_NAME: "",
      CALL_DURATION: "6",
      RECEIVER_MOBILE: "9253186178",
    },
    {
      UNIQUE_QUERY_ID: "98720688",
      QUERY_TYPE: "P",
      QUERY_TIME: "2023-09-11 17:02:15",
      SENDER_NAME: "Furqan Ahmad",
      SENDER_MOBILE: "+91-9359364545",
      SENDER_EMAIL: "kohinoorfurqan@yahoo.com",
      SUBJECT: "Buyer Call",
      SENDER_COMPANY: "Kohinoor Enterprises",
      SENDER_ADDRESS:
        "Shop no.- 31/300, Collectorate Road,  Agra  Saghir Fatima College, Agra, Uttar Pradesh,         282003",
      SENDER_CITY: "Agra",
      SENDER_STATE: "Uttar Pradesh",
      SENDER_PINCODE: "282003",
      SENDER_COUNTRY_ISO: "IN",
      SENDER_MOBILE_ALT: "+91-8923545861",
      SENDER_PHONE: "",
      SENDER_PHONE_ALT: "",
      SENDER_EMAIL_ALT: "",
      QUERY_PRODUCT_NAME: "",
      QUERY_MESSAGE: "",
      QUERY_MCAT_NAME: "",
      CALL_DURATION: "118",
      RECEIVER_MOBILE: "9667316033",
    },
    {
      UNIQUE_QUERY_ID: "2547954328",
      QUERY_TYPE: "W",
      QUERY_TIME: "2023-09-11 22:13:36",
      SENDER_NAME: "Syed Sayar",
      SENDER_MOBILE: "+91-7006348369",
      SENDER_EMAIL: "xaid.safaan@gmail.com",
      SUBJECT: "Requirement for U Cut Non Woven Bags",
      SENDER_COMPANY: "disposable",
      SENDER_ADDRESS: "Narbal, Budgam, Jammu & Kashmir,         193401",
      SENDER_CITY: "Budgam",
      SENDER_STATE: "Jammu & Kashmir",
      SENDER_PINCODE: "193401",
      SENDER_COUNTRY_ISO: "IN",
      SENDER_MOBILE_ALT: "",
      SENDER_PHONE: "",
      SENDER_PHONE_ALT: "",
      SENDER_EMAIL_ALT: "",
      QUERY_PRODUCT_NAME: "U Cut Non Woven Bags",
      QUERY_MESSAGE:
        "I am interested in U Cut Non Woven Bags<br>Quantity : 100 Kg<br>",
      QUERY_MCAT_NAME: "Non Woven U Cut Bag",
      CALL_DURATION: "",
      RECEIVER_MOBILE: "",
    },
  ],
};

export default data;
